sudo: required
group: deprecated-2017Q3
language: scala
scala:
  - 2.11.8
services:
  - docker

notifications:
  email: false
  webhooks:
    urls:
      # travis2slack webhook to enable DMs on openwhisk-team.slack.com to PR authors with TravisCI results
      secure: ZE3Y6k7io6D13CsP45gDGpIVToQbucSftdDmZicreSK9+TjBjMG90GPEGc1BXSyfQEgmmvZ2eHuL2iuA9cbrY/exX14YMzrT7ejh9YhvS2QDjMazvp7PigSVp05BiixppmWEAYiituPxAONr80mXxMKSUQBTqdoqaiIOVkMURMOvxg3n5iwSLQgTZrV+eaVjCcgJ4WWIFgrktr+Dpo6qd7IBc7cM+Wfk5WKhP9arXY59KPxKeB8Ksy2+geOspyZjLM3dEKhx2IfUkwtf4L3aW9LQewglWdGrsOt3S+vpGbMhvviua1HQsC8Al8TY5FnSfd9wM2x9hyZbFT7omz7/em8zuGZQi5C3NNCgRoHjlg0ccp9Kqh3ulIDAMhcTG+yYqo1y420HV4kdneuDbF+nyNnU+ouswgSwWlCUOSbwnprW3B39qui/8l9ktB/rOI7J76hlRj5ke0oi7bfEbcNSSFlTyZwHq6zzWXprSdXJAnT3DomN/rwTb+RiqA9T+G6TafmSB7ay4nmxzcuzTmMYQw3RCrXK9Uk7XzGCPvcquoimK5x13bi8yV2AjTw9rPy2xLsG0Yyn/ltnlbD7oDBWAdMkJZO/4s/STCJOUff05k94r62333pqKsP7sYoUX3bJuNoMvUr1GMSX1ydu7FEcBQG2ItDJKWl0uNWHI+o6pZ8=

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K "$encrypted_DF18CF3F552A_key" -iv "$encrypted_DF18CF3F552A_iv" -in tests/credentials.json.enc -out tests/credentials.json -d; fi'
  - "./tools/travis/setup.sh"
install: true
script:
  - "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
  - provider: script
    script: "./tools/travis/publish.sh ibmfunctions ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
    on:
      tags: true
      all_branches: true
      repo: ibm-functions/runtime-swift
  - provider: script
    script: "./tools/travis/publish.sh ibmfunctions 4.1 master && ./tools/travis/publish.sh ibmfunctions 4.2 master "
    on:
      branch: master
      repo: ibm-functions/runtime-swift
env:
  global:
  - secure: dndDlFixUN9sua36GlNYq43GucaPmQxQaGtqnRAToKDihTwXqDLksWw8OoXnBqnWMJu/X8j2cx1EAiFmDRO5RdOlILoOx2TqsIEN4Xeu6egLTqr9gri494AuhGC09MLOfVVXW5RsJY2I2D3PoehTNC4u9HxXYJMZp/0Y3kBok+ADp5O3TzC0e5DLFIsQcRxWo81tJ6qraI4xILej8LYPubLT1Zh9hmvWXtXl666gNTrV9vDAROtDU4fAfkv44tv5n5MJNUZWzyYhPpUcmnSetlBVxyX+SrTqvabCYmY0Vg7EvSc6a7fA5YoLpockA2K2VA9+q1Pzns3nDOdVUbt/rRiA5W6+Q5/JH5WkqnjZlGSoez0KXATA4CoSwBXCxuoqwfXlZyEnE71rZv/Kspeeb03I3GQbVihRN0NoAKJwK7AVJMPo4CLLz8WXBWd4Lg4BtTOasZi7gx4jitQ3akfNobxfA0YEb+jNQtRGFuP7KKwfyiz7xuuQoh6X+Q6mOgI/jHBqbilMDYaHLuVc7Avu6BL2UeKw82T1iru74qk2evebRxBaAvp4S0icPYcbBu6gMvNfwU1gj814o61tCn8eBKRR/fKWYSf6TwjutnZ+JRedNYUQA5JSZyQOzJQvQIEZoh8fTACnBJ/QJ6R2DtTGsI17A/ZLLHwM49uP4lVrKm4=
  - secure: lTMQ9GZ4heAK4hBC17C+Pz4e8bMOo0Elrpcoz2CdiznkhlguWZpn9+RMjk0VVjpr7nh1ubefDa+qhPg7pBH1PQJ+/vbvfhhzkhowj1DL0oraBoz16QJdIkaBZX+QFt5WMuSnOQJDSr3BPUlclqlC/f+15XDBjKPPhfQkgft7Gbz3o5XiNEV5NJNC0aGYhvvoRETBcfP3U0N40Bljr2I8EaDQH6rzyoFlKyANwaqIDj1F6plfq0Zr22GvLJfhZg6fR+IMMHAvAn9CI4CP27yBfC8ylJhIvy5hKFgZ2CzhWUoauDjZrfQgQs6WW5SzuqUeUc6dU7e6se1GzehemptsSrLznLZi+tx/clQdk0aKwgHR1cpFwGauzeFP8wnU/zG1ID4Z4G77XhIl9uhZdHzdPtm00OCyOUPlLQf9wuKh1LNA++zZvOjslWQHWmBQybMfoqNAw3lQTS3L4CFc4VoGmQhjOABm3Z9TmoTcW0nWNqziwZpC1GBvCgt/1QdQX97/BRCt3kp091g80pI+Ztday+kIhCnpkSCRkhQW+Eymd2DLRsVhSoJZ9WlAAvkxaKmbX4xvdedoWjsCzPUQWxl5/mpT9sxlCS7HrSadMLaNHMao9BZYBVDgGpj9S9wkMi0eR58A0HDSwCpk6RGQ4nbdULwwDpfWQ/xNKmgcAtVD2L4=
