# Dockerfile for swift actions, overrides and extends ActionRunner from actionProxy
# TODO replace with openwhisk/action-swift-v4.0
FROM openwhisk/action-swift-v4.0:1.0.1

# Add Pre-Installed Pacakges for IBM
ADD spm-build/Package.swift /swift4Action/spm-build
