# Dockerfile for swift actions, overrides and extends ActionRunner from actionProxy
FROM openwhisk/action-swift-v4.1:0.1.0

# Add Pre-Installed Pacakges for IBM
ADD spm-build/Package.swift /swift4Action/spm-build
